"""initial_schema

Revision ID: 138dcbc0afd4
Revises: 
Create Date: 2026-04-07 09:46:38.824158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '138dcbc0afd4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EXPECTED_TABLES = {
    'audit_logs',
    'ip_claims',
    'ip_documents',
    'ip_reviews',
    'kyc_cases',
    'kyc_funnel_stats',
    'otp_codes',
    'patent_cache',
    'patent_documents',
    'patent_metrics_daily',
    'patent_reviews',
    'patent_search_cache',
    'patents',
    'profiles',
    'sanctions_checks',
    'token_revocations',
    'user_metrics_daily',
    'users',
    'verification_cases',
    'wallet_links',
    'webhook_events',
}


def _schema_already_present() -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    return EXPECTED_TABLES.issubset(existing_tables)


def upgrade() -> None:
    if _schema_already_present():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_funnel_stats',
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('step_name', sa.Enum('registered', 'kyc_started', 'kyc_manual_review', 'kyc_approved', 'kyc_rejected', name='kyc_funnel_step'), nullable=False),
    sa.Column('users_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('period_start', 'period_end', 'step_name')
    )
    op.create_index('ix_kyc_funnel_stats_period', 'kyc_funnel_stats', ['period_start', 'period_end'], unique=False)
    op.create_index('ix_kyc_funnel_stats_step', 'kyc_funnel_stats', ['step_name'], unique=False)
    op.create_table('patent_metrics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_patents', sa.Integer(), nullable=False),
    sa.Column('new_patents', sa.Integer(), nullable=False),
    sa.Column('patents_under_review', sa.Integer(), nullable=False),
    sa.Column('patents_approved', sa.Integer(), nullable=False),
    sa.Column('patents_rejected', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('patent_search_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=True),
    sa.Column('date_from', sa.String(length=20), nullable=True),
    sa.Column('date_to', sa.String(length=20), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('sources_queried', sa.JSON(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patent_search_cache_expires', 'patent_search_cache', ['expires_at'], unique=False)
    op.create_index('ix_patent_search_cache_query', 'patent_search_cache', ['query_hash'], unique=False)
    op.create_table('token_revocations',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index('ix_token_revocations_expires_at', 'token_revocations', ['expires_at'], unique=False)
    op.create_table('user_metrics_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=False),
    sa.Column('new_users', sa.Integer(), nullable=False),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('kyc_started', sa.Integer(), nullable=False),
    sa.Column('kyc_approved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider_ref', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('investor', 'issuer', 'admin', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('pending_otp', 'active', 'suspended', 'blocked', 'rejected', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('received', 'processed', 'failed', 'dead_letter', name='webhook_event_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_webhook_events_source_external', 'webhook_events', ['source', 'external_id'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('ip_claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issuer_user_id', sa.Uuid(), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=False),
    sa.Column('patent_title', sa.String(length=512), nullable=True),
    sa.Column('claimed_owner_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'prechecked', 'awaiting_kyc', 'under_review', 'approved', 'rejected', name='ip_claim_status'), nullable=False),
    sa.Column('prechecked', sa.Boolean(), nullable=False),
    sa.Column('precheck_status', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=128), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patent_metadata', sa.JSON(), nullable=True),
    sa.Column('external_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issuer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_claims_issuer', 'ip_claims', ['issuer_user_id'], unique=False)
    op.create_index('ix_ip_claims_patent_number', 'ip_claims', ['patent_number'], unique=False)
    op.create_index('ix_ip_claims_status', 'ip_claims', ['status'], unique=False)
    op.create_table('kyc_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_case_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'pending', 'needs_input', 'manual_review', 'approved', 'rejected', 'expired', name='kyc_case_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'unknown', name='kyc_risk_level'), nullable=True),
    sa.Column('review_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_case_id', name='uq_kyc_cases_provider_case')
    )
    op.create_index('ix_kyc_cases_provider_case', 'kyc_cases', ['provider', 'provider_case_id'], unique=False)
    op.create_index('ix_kyc_cases_status', 'kyc_cases', ['status'], unique=False)
    op.create_index('ix_kyc_cases_user_id', 'kyc_cases', ['user_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_codes_code', 'otp_codes', ['code'], unique=False)
    op.create_index('ix_otp_codes_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index('ix_otp_codes_user_id', 'otp_codes', ['user_id'], unique=False)
    op.create_table('patents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'prechecked', 'under_review', 'approved', 'rejected', 'archived', name='patent_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patent_number', 'jurisdiction', name='uq_patents_number_jurisdiction')
    )
    op.create_index('ix_patents_owner_user_id', 'patents', ['owner_user_id'], unique=False)
    op.create_index('ix_patents_status', 'patents', ['status'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('sanctions_checks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'clear', 'matches_found', 'manual_review', 'failed', name='sanction_check_status'), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sanctions_checks_checked_at', 'sanctions_checks', ['checked_at'], unique=False)
    op.create_index('ix_sanctions_checks_user_id', 'sanctions_checks', ['user_id'], unique=False)
    op.create_table('verification_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('patent_name', sa.String(length=255), nullable=True),
    sa.Column('patent_address', sa.String(length=500), nullable=True),
    sa.Column('user_address', sa.String(length=500), nullable=True),
    sa.Column('id_document_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'pending', 'approved', 'rejected', name='verification_status'), nullable=False),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_verification_cases_status', 'verification_cases', ['status'], unique=False)
    op.create_index('ix_verification_cases_user_id', 'verification_cases', ['user_id'], unique=False)
    op.create_table('wallet_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_address', sa.String(length=100), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address', 'network', name='uq_wallet_links_address_network')
    )
    op.create_index('ix_wallet_links_user_id', 'wallet_links', ['user_id'], unique=False)
    op.create_index(
        'uix_wallet_links_user_network_primary',
        'wallet_links',
        ['user_id', 'network'],
        unique=True,
        postgresql_where=sa.text('is_primary IS TRUE'),
    )
    op.create_table('ip_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_claim_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ip_claim_id'], ['ip_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_documents_claim', 'ip_documents', ['ip_claim_id'], unique=False)
    op.create_index('ix_ip_documents_uploader', 'ip_documents', ['created_by_user_id'], unique=False)
    op.create_table('ip_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ip_claim_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('approve', 'reject', 'request_more_data', name='ip_review_decision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ip_claim_id'], ['ip_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ip_reviews_claim', 'ip_reviews', ['ip_claim_id'], unique=False)
    op.create_index('ix_ip_reviews_reviewer', 'ip_reviews', ['reviewer_id'], unique=False)
    op.create_table('patent_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('USPTO', 'PATENTSVIEW', 'EPO_OPS', 'WIPO_PCT', name='patent_cache_source'), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=False),
    sa.Column('kind_code', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.String(length=20), nullable=True),
    sa.Column('publication_date', sa.String(length=20), nullable=True),
    sa.Column('grant_date', sa.String(length=20), nullable=True),
    sa.Column('patent_status', sa.String(length=32), nullable=True),
    sa.Column('assignees', sa.JSON(), nullable=True),
    sa.Column('inventors', sa.JSON(), nullable=True),
    sa.Column('cpc_classes', sa.JSON(), nullable=True),
    sa.Column('uspc_classes', sa.JSON(), nullable=True),
    sa.Column('ipc_classes', sa.JSON(), nullable=True),
    sa.Column('geo_data', sa.JSON(), nullable=True),
    sa.Column('family_ids', sa.JSON(), nullable=True),
    sa.Column('citations_count', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('cache_status', sa.Enum('valid', 'expired', 'error', name='patent_cache_status'), nullable=False),
    sa.Column('cached_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('ip_claim_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['ip_claim_id'], ['ip_claims.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_patent_cache_source_id')
    )
    op.create_index('ix_patent_cache_cache_status', 'patent_cache', ['cache_status'], unique=False)
    op.create_index('ix_patent_cache_country_number', 'patent_cache', ['country_code', 'patent_number'], unique=False)
    op.create_index('ix_patent_cache_expires', 'patent_cache', ['expires_at'], unique=False)
    op.create_table('patent_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patent_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.Enum('application', 'grant', 'supporting', 'ownership_proof', name='document_type'), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patent_documents_created_by', 'patent_documents', ['created_by_user_id'], unique=False)
    op.create_index('ix_patent_documents_patent_id', 'patent_documents', ['patent_id'], unique=False)
    op.create_table('patent_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patent_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_user_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.Enum('approved', 'rejected', 'needs_more_info', 'invalid', name='review_decision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patent_reviews_patent_id', 'patent_reviews', ['patent_id'], unique=False)
    op.create_index('ix_patent_reviews_reviewed_at', 'patent_reviews', ['reviewed_at'], unique=False)
    op.create_index('ix_patent_reviews_reviewer', 'patent_reviews', ['reviewer_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patent_reviews_reviewer', table_name='patent_reviews')
    op.drop_index('ix_patent_reviews_reviewed_at', table_name='patent_reviews')
    op.drop_index('ix_patent_reviews_patent_id', table_name='patent_reviews')
    op.drop_table('patent_reviews')
    op.drop_index('ix_patent_documents_patent_id', table_name='patent_documents')
    op.drop_index('ix_patent_documents_created_by', table_name='patent_documents')
    op.drop_table('patent_documents')
    op.drop_index('ix_patent_cache_expires', table_name='patent_cache')
    op.drop_index('ix_patent_cache_country_number', table_name='patent_cache')
    op.drop_index('ix_patent_cache_cache_status', table_name='patent_cache')
    op.drop_table('patent_cache')
    op.drop_index('ix_ip_reviews_reviewer', table_name='ip_reviews')
    op.drop_index('ix_ip_reviews_claim', table_name='ip_reviews')
    op.drop_table('ip_reviews')
    op.drop_index('ix_ip_documents_uploader', table_name='ip_documents')
    op.drop_index('ix_ip_documents_claim', table_name='ip_documents')
    op.drop_table('ip_documents')
    op.drop_index('uix_wallet_links_user_network_primary', table_name='wallet_links', postgresql_where='is_primary IS TRUE')
    op.drop_index('ix_wallet_links_user_id', table_name='wallet_links')
    op.drop_table('wallet_links')
    op.drop_index('ix_verification_cases_user_id', table_name='verification_cases')
    op.drop_index('ix_verification_cases_status', table_name='verification_cases')
    op.drop_table('verification_cases')
    op.drop_index('ix_sanctions_checks_user_id', table_name='sanctions_checks')
    op.drop_index('ix_sanctions_checks_checked_at', table_name='sanctions_checks')
    op.drop_table('sanctions_checks')
    op.drop_table('profiles')
    op.drop_index('ix_patents_status', table_name='patents')
    op.drop_index('ix_patents_owner_user_id', table_name='patents')
    op.drop_table('patents')
    op.drop_index('ix_otp_codes_user_id', table_name='otp_codes')
    op.drop_index('ix_otp_codes_expires_at', table_name='otp_codes')
    op.drop_index('ix_otp_codes_code', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('ix_kyc_cases_user_id', table_name='kyc_cases')
    op.drop_index('ix_kyc_cases_status', table_name='kyc_cases')
    op.drop_index('ix_kyc_cases_provider_case', table_name='kyc_cases')
    op.drop_table('kyc_cases')
    op.drop_index('ix_ip_claims_status', table_name='ip_claims')
    op.drop_index('ix_ip_claims_patent_number', table_name='ip_claims')
    op.drop_index('ix_ip_claims_issuer', table_name='ip_claims')
    op.drop_table('ip_claims')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_source_external', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_metrics_daily')
    op.drop_index('ix_token_revocations_expires_at', table_name='token_revocations')
    op.drop_table('token_revocations')
    op.drop_index('ix_patent_search_cache_query', table_name='patent_search_cache')
    op.drop_index('ix_patent_search_cache_expires', table_name='patent_search_cache')
    op.drop_table('patent_search_cache')
    op.drop_table('patent_metrics_daily')
    op.drop_index('ix_kyc_funnel_stats_step', table_name='kyc_funnel_stats')
    op.drop_index('ix_kyc_funnel_stats_period', table_name='kyc_funnel_stats')
    op.drop_table('kyc_funnel_stats')
    # ### end Alembic commands ###
